git:
  parseEmoji: true
gui:
  nerdFontsVersion: "3"
customCommands:
  - key: "<c-c>"
    context: files
    description: Commit changes using gitmojis
    prompts:
    - command: gitmoji -l
      filter: ^(.*?) - (:.*?:) - (.*)$
      key: emoji
      labelFormat: '{{ .group_1 }} - {{ .group_3 }}'
      title: 'Choose a gitmoji: '
      type: menuFromCommand
      valueFormat: '{{ .group_2 }}'
    - key: scope
      title: 'Enter the scope of current changes: '
      type: input
    - key: title
      title: 'Enter the commit title: '
      type: input
    - key: message
      title: 'Enter the commit body: '
      type: input
    command: "git commit -m '{{ .Form.emoji }} {{ if .Form.scope }}({{ .Form.scope }}):{{ end }} {{ .Form.title }}' {{ if .Form.message }} -m '{{ .Form.message }}'{{ end }}"
    loadingText: "Creating gitmojis commit..."
